### ISSUE TITLE
Add credits kontol

### ISSUE THREAD

**Issue by tomyprs** [Developed-Bots/Protector#1]

**Comment by Kunal-Diwan** [comment]
This is ours repository so why we will give Credits to others 🤣. And this repository is not even completed .

**Comment by Kunal-Diwan** [comment]
@Kunal-Diwan Hi

**Comment by MR-JINN-OF-TG** [comment]
Those where silly guys bro.

**Comment by Kunal-Diwan** [comment]
Hmm
